on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --exclude=".git" --exclude=".github"
        path: /
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.PORT }}
